### ISSUE TITLE
Corn TEA/prices not working

### ISSUE THREAD

**Issue by daltonwstewart** [BioSTEAMDevelopmentGroup/BLocS#1]
Hi @yoelcortes,

I'm having another problem with the TEA that I think might be related to feedstock prices. When I run `eval_by_state.py` (the file we were working with last week) for the corn biorefinery this time, I get the same error we were seeing with the sugarcane biorefinery: `RuntimeError: minimum tolerance reached; root could not be solved`. 

I think it's calling the proper number this time, but it doesn't seem to be able to solve for the MESP. Can you figure out what's going wrong? Thank you!

**Comment by yoelcortes** [comment]
Hi @dstew16, could you provide the tracebacks for each issue and the file name you ran? Also, don't forget to update to the latest biorefineries/biosteam/thermosteam on github (git pull). If you have local changes on biosteam you can `run git restore .`.

You may also need to `pip install free_properties==0.3.4` Since dependencies are not automatically updated when you pull.

Thanks!

**Comment by daltonwstewart** [comment]
Hi @yoelcortes,

I'm going to post the tracebacks before I update/install anything in case it's something you want to look into even if updates/installations seem to fix the problem.

This issue happens when I run `evaluate_SS('corn')` in `eval_by_state.py`. This is the entire traceback, it looks like it keeps repeating, maybe for each simulation I'm trying to run with the function:

`Traceback (most recent call last):

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 942, in solve_sales
    maxiter=1000, args=args, checkiter=True)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/open_solvers.py", line 85, in aitken_secant
    if checkroot or checkiter: utils.raise_tol_error()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/utils.py", line 200, in raise_tol_error
    raise RuntimeError('minimum tolerance reached; root could not be solved')

RuntimeError: minimum tolerance reached; root could not be solved


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 906, in solve_price
    sales = self.solve_sales()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 951, in solve_sales
    maxiter=1000, args=args, checkiter=True)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/open_solvers.py", line 85, in aitken_secant
    if checkroot or checkiter: utils.raise_tol_error()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/utils.py", line 200, in raise_tol_error
    raise RuntimeError('minimum tolerance reached; root could not be solved')

RuntimeError: minimum tolerance reached; root could not be solved


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 942, in solve_sales
    maxiter=1000, args=args, checkiter=True)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/open_solvers.py", line 85, in aitken_secant
    if checkroot or checkiter: utils.raise_tol_error()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/utils.py", line 200, in raise_tol_error
    raise RuntimeError('minimum tolerance reached; root could not be solved')

RuntimeError: minimum tolerance reached; root could not be solved


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/daltonstewart/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/eval_by_state.py", line 190, in solve_price
    MFSP = tea.solve_price(tea.ethanol_product)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 910, in solve_price
    sales = self.solve_sales()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 951, in solve_sales
    maxiter=1000, args=args, checkiter=True)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/open_solvers.py", line 85, in aitken_secant
    if checkroot or checkiter: utils.raise_tol_error()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/utils.py", line 200, in raise_tol_error
    raise RuntimeError('minimum tolerance reached; root could not be solved')

RuntimeError: minimum tolerance reached; root could not be solved


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/evaluation/_model.py", line 327, in _evaluate_sample
    return [i() for i in self.metrics]

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/evaluation/_model.py", line 327, in <listcomp>
    return [i() for i in self.metrics]

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/evaluation/_metric.py", line 40, in __call__
    self.cache = self.getter()

  File "/Users/daltonstewart/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/eval_by_state.py", line 211, in MFSP
    return solve_price()

  File "/Users/daltonstewart/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/eval_by_state.py", line 192, in solve_price
    MFSP = tea.solve_price([tea.ethanol_product], [4])

TypeError: solve_price() takes 2 positional arguments but 3 were given


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 942, in solve_sales
    maxiter=1000, args=args, checkiter=True)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/open_solvers.py", line 85, in aitken_secant
    if checkroot or checkiter: utils.raise_tol_error()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/utils.py", line 200, in raise_tol_error
    raise RuntimeError('minimum tolerance reached; root could not be solved')

RuntimeError: minimum tolerance reached; root could not be solved


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 906, in solve_price
    sales = self.solve_sales()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 951, in solve_sales
    maxiter=1000, args=args, checkiter=True)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/open_solvers.py", line 85, in aitken_secant
    if checkroot or checkiter: utils.raise_tol_error()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/utils.py", line 200, in raise_tol_error
    raise RuntimeError('minimum tolerance reached; root could not be solved')

RuntimeError: minimum tolerance reached; root could not be solved


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 942, in solve_sales
    maxiter=1000, args=args, checkiter=True)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/open_solvers.py", line 85, in aitken_secant
    if checkroot or checkiter: utils.raise_tol_error()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/utils.py", line 200, in raise_tol_error
    raise RuntimeError('minimum tolerance reached; root could not be solved')

RuntimeError: minimum tolerance reached; root could not be solved


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-2-91baab865dd8>", line 1, in <module>
    evaluate_SS('corn')

  File "/Users/daltonstewart/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/eval_by_state.py", line 505, in evaluate_SS
    model.evaluate()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/evaluation/_model.py", line 321, in evaluate
    values[i] = evaluate(samples[i], thorough, **dyn_sim_kwargs)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/evaluation/_model.py", line 336, in _evaluate_sample
    values = self._exception_hook(new_exception, sample)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/evaluation/_model.py", line 103, in raise_exception
    def raise_exception(exception, sample): raise exception

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/evaluation/_model.py", line 333, in _evaluate_sample
    return [i() for i in self.metrics]

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/evaluation/_model.py", line 333, in <listcomp>
    return [i() for i in self.metrics]

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/evaluation/_metric.py", line 40, in __call__
    self.cache = self.getter()

  File "/Users/daltonstewart/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/eval_by_state.py", line 290, in MFSP_baseline
    MFSP = 2.98668849 * tea.solve_price(tea.ethanol_product)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 910, in solve_price
    sales = self.solve_sales()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/biosteam/_tea.py", line 951, in solve_sales
    maxiter=1000, args=args, checkiter=True)

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/open_solvers.py", line 85, in aitken_secant
    if checkroot or checkiter: utils.raise_tol_error()

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/flexsolve/utils.py", line 200, in raise_tol_error
    raise RuntimeError('minimum tolerance reached; root could not be solved')

RuntimeError: minimum tolerance reached; root could not be solved`

**Comment by yoelcortes** [comment]
Hi @dstew16, 

I made the `TEA.solve_price` method even more robust with the latest biosteam (on github). It should work now.

Also, the units of measure for some prices are set in USD/ton, but the units say "USD/kg":
https://github.com/BioSTEAMDevelopmentGroup/BLocS/blob/aeded4104291cc2aa37b208e092ea013b3fb4f9f/blocs/incentives/eval_by_state.py#L319
You may want to fix it to say "USD/ton", or remove the kg_per_ton factors to keep it at USD/kg.

Hope this helps!

**Comment by daltonwstewart** [comment]
Seems to be working great now! I did notice that the magnitudes of the prices didn't seem to match with the units haha, it's fixed now. Thanks for all your help!

**Comment by daltonwstewart** [comment]
Hi @yoelcortes,

Unfortunately the `corn` biorefinery is no longer working when I try a different analysis. Previously I was getting a `RuntimeError` about the minimum tolerance being reached like the one above, but I just cloned the latest biosteam, thermosteam, and biorefineries, and am now getting this error:

Traceback (most recent call last):

  Input In [2] in <cell line: 1>
    table=evaluate_IP('corn')

  File ~/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/evaluation.py:813 in evaluate_IP
    model = create_IPs_model(biorefinery)

  File ~/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/evaluation.py:497 in create_IPs_model
    tea = blc.create_corn_tea()

  File ~/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/incentives_tea.py:24 in create_corn_tea
    tea = cn.create_tea(cn.corn_sys, cls=ConventionalIncentivesTEA)

  File ~/Dropbox/Stewart-Guest_Shared/Code/biorefineries/corn/__init__.py:73 in __getattr__
    _load_system()

  File ~/Dropbox/Stewart-Guest_Shared/Code/biorefineries/corn/__init__.py:61 in _load_system
    corn_sys.simulate()

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/_system.py:1702 in simulate
    else: self._converge()

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/_system.py:1419 in _converge
    self._run()

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/_system.py:1373 in _run
    if isa(i, Unit): run(i, i.run)

  File ~/Dropbox/Stewart-Guest_Shared/Code/thermosteam/exceptions.py:78 in try_method_with_object_stamp
    raise_error_with_object_stamp(object, error)

  File ~/Dropbox/Stewart-Guest_Shared/Code/thermosteam/exceptions.py:70 in raise_error_with_object_stamp
    raise error

  File ~/Dropbox/Stewart-Guest_Shared/Code/thermosteam/exceptions.py:74 in try_method_with_object_stamp
    return method(*args)

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/_unit.py:785 in run
    self._run()

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/units/drying.py:128 in _run
    sep.adjust_moisture_content(dry_solids, hot_air, self.moisture_content, self.moisture_ID)

TypeError: <DrumDryer: D610> adjust_moisture_content() takes 3 positional arguments but 4 were given



This error occurs when I try to run [evaluate_IP](https://github.com/BioSTEAMDevelopmentGroup/BLocS/blob/f52582f61021ca8ea4edc834aedcba6d89b04d8b/blocs/incentives/evaluation.py#L808)

I'm not sure why it's having trouble with this corn price when the other evaluation function worked, but I appreciate you looking into it. We're very close to wrapping up this manuscript! Thank you!

**Comment by yoelcortes** [comment]
Sorry! I was making updates for another project and for got to push thermosteam to github. Try pulling thermosteam again, I think it should work now.

**Comment by daltonwstewart** [comment]
Now I am back to getting this error:

Traceback (most recent call last):

  Input In [2] in <cell line: 1>
    table=evaluate_IP('corn')

  File ~/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/evaluation.py:818 in evaluate_IP
    model.evaluate()

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/evaluation/_model.py:321 in evaluate
    values[i] = evaluate(samples[i], thorough, **dyn_sim_kwargs)

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/evaluation/_model.py:336 in _evaluate_sample
    values = self._exception_hook(new_exception, sample)

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/evaluation/_model.py:102 in raise_exception
    def raise_exception(exception, sample): raise exception

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/evaluation/_model.py:333 in _evaluate_sample
    return [i() for i in self.metrics]

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/evaluation/_model.py:333 in <listcomp>
    return [i() for i in self.metrics]

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/evaluation/_metric.py:40 in __call__
    self.cache = self.getter()

  File ~/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/evaluation.py:598 in MFSP_baseline
    MFSP_baseline_box[0] = MFSP = 2.98668849 * tea.solve_price(tea.ethanol_product)

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/_tea.py:910 in solve_price
    sales = self.solve_sales()

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/_tea.py:946 in solve_sales
    if x0 == 0: raise e from None

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/_tea.py:943 in solve_sales
    sales = flx.aitken_secant(f, x0, x1, xtol=10, ytol=1000.,

  File ~/anaconda3/envs/py38/lib/python3.8/site-packages/flexsolve/open_solvers.py:85 in aitken_secant
    if checkroot or checkiter: utils.raise_tol_error()

  File ~/anaconda3/envs/py38/lib/python3.8/site-packages/flexsolve/utils.py:200 in raise_tol_error
    raise RuntimeError('minimum tolerance reached; root could not be solved')

RuntimeError: minimum tolerance reached; root could not be solved

**Comment by yoelcortes** [comment]
Hi Dalton, it should be working now with my latest commit to BLocS, let me know if you run into anything else~

**Comment by daltonwstewart** [comment]
Hi Yoel,

The solver will converge to a solution now, but the solution just ends up being the upper bound of the bracket you specify in the solver (so I am getting MESPs around $10/gal).

I just checked again, and this problem is only occurring for the `corn` biorefinery when I use `evaluate_IP`. The other two biorefineries work fine with evaluate_IP and all three work with evaluate_SS. I think it must have something to do with how the model is set up or how the corn prices are being used. I'll try and take a look through the model and would appreciate any thoughts or input from you. Maybe we can discuss in person later in the week. Thanks!

**Comment by yoelcortes** [comment]
Hi Dalton, it should work now for real. Sorry about that! I had set the solver tolerance for the price to 1000, which is nonsense (I fixed it to 1e-3). I would be happy to meet later this week if you find any more issues (or if the same issue pops out again). Thanks again for sharing all the details.

**Comment by daltonwstewart** [comment]
It's working now! Thanks for your help!
